version: '3.5'
services:
  nextjs-app:
    image: karlakonsult-image
    build:
      context: .
      dockerfile: Dockerfile
    container_name: karlakonsult
    environment:
      - NODE_ENV=production
      - PORT=3000
      - TZ=Europe/Stockholm
    ports:
      - 32789:3000
    restart: unless-stopped
