import { Inter } from "next/font/google";
import styled from "styled-components";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <main>{children}</main>

      <Footer>
        <LogoContainer>
          <Image
            src="/karla-logo.png"
            alt="logo"
            width={105}
            height={158}
            style={{ objectFit: "contain" }}
          />
        </LogoContainer>
        <InfoContainer>
          <p>Karla Projektkonsult AB</p>
          <p>info@karlakonsult.se</p>
        </InfoContainer>
      </Footer>
    </>
  );
}

const Footer = styled.footer`
  background-color: #242424;
  color: white;
  position: relative;
  display: flex;
  justify-content: end;
  align-items: center;
  width: 100%;
  height: 125px;
  overflow: hidden;
  z-index: 0;
  box-shadow: inset 0px 4px 4px rgba(0, 0, 0, 0.25); /* Inner shadow */
`;

const LogoContainer = styled.div`
  position: absolute;
  bottom: -40px;
  left: 0;
`;

const InfoContainer = styled.div`
  text-align: right;
  padding-right: 10px;
`;
